// Package email manages mailbox and forwarder definitions and exports
// configuration for Go-native mail servers (maddy, go-guerrilla).
package email

import (
	"fmt"
	"net/mail"
	"sort"
	"strings"

	"github.com/schmorrison/goshpanel/internal/store"
)

// ValidateAddress checks that addr is a plain email address.
func ValidateAddress(addr string) error {
	parsed, err := mail.ParseAddress(addr)
	if err != nil || parsed.Address != addr {
		return fmt.Errorf("invalid email address %q", addr)
	}
	return nil
}

// Domains returns the unique domains covered by the mailboxes.
func Domains(boxes []store.Mailbox) []string {
	seen := map[string]bool{}
	for _, m := range boxes {
		if i := strings.LastIndex(m.Address, "@"); i >= 0 {
			seen[m.Address[i+1:]] = true
		}
	}
	out := make([]string, 0, len(seen))
	for d := range seen {
		out = append(out, d)
	}
	sort.Strings(out)
	return out
}

// RenderMaddyConfig produces a minimal maddy configuration covering the
// mailbox domains, plus alias lines for forwarders. Credentials are
// provisioned separately via maddyctl; the panel stores argon2id hashes.
func RenderMaddyConfig(boxes []store.Mailbox, fwds []store.EmailForwarder, hostname string) string {
	domains := Domains(boxes)

	var b strings.Builder
	b.WriteString("# maddy configuration generated by GoshPanel — do not edit by hand.\n\n")
	fmt.Fprintf(&b, "$(hostname) = %s\n", hostname)
	if len(domains) > 0 {
		fmt.Fprintf(&b, "$(primary_domain) = %s\n", domains[0])
		fmt.Fprintf(&b, "$(local_domains) = %s\n", strings.Join(domains, " "))
	}
	b.WriteString(`
tls off

auth.pass_table local_authdb {
    table sql_table {
        driver sqlite3
        dsn credentials.db
        table_name passwords
    }
}

storage.imapsql local_mailboxes {
    driver sqlite3
    dsn imapsql.db
}

smtp tcp://0.0.0.0:25 {
    hostname $(hostname)
    destination $(local_domains) {
        deliver_to &local_mailboxes
    }
}

submission tcp://0.0.0.0:587 {
    hostname $(hostname)
    auth &local_authdb
    deliver_to &local_mailboxes
}

imap tcp://0.0.0.0:143 {
    auth &local_authdb
    storage &local_mailboxes
}
`)
	if len(fwds) > 0 {
		b.WriteString("\n# Forwarders (aliases):\n")
		for _, f := range fwds {
			fmt.Fprintf(&b, "#   %s -> %s\n", f.From, f.To)
		}
	}
	if len(boxes) > 0 {
		b.WriteString("\n# Mailboxes to provision with maddyctl:\n")
		for _, m := range boxes {
			fmt.Fprintf(&b, "#   maddyctl creds create %s && maddyctl imap-acct create %s\n", m.Address, m.Address)
		}
	}
	return b.String()
}
