// Package dns validates zone records and renders RFC 1035 zone files —
// the cPanel Zone Editor equivalent. The generated files can be served by
// any DNS server (CoreDNS is the Go-native choice).
package dns

import (
	"fmt"
	"net"
	"strings"
	"time"

	"github.com/schmorrison/goshpanel/internal/store"
)

// RecordTypes lists the supported record types.
var RecordTypes = []string{"A", "AAAA", "CNAME", "MX", "TXT", "NS", "SRV"}

// Validate checks a DNS record for type-specific correctness.
func Validate(r store.DNSRecord) error {
	if r.Name == "" {
		return fmt.Errorf("record name is required")
	}
	if r.TTL < 0 {
		return fmt.Errorf("ttl must be non-negative")
	}
	switch r.Type {
	case "A":
		ip := net.ParseIP(r.Value)
		if ip == nil || ip.To4() == nil {
			return fmt.Errorf("A record requires an IPv4 address, got %q", r.Value)
		}
	case "AAAA":
		ip := net.ParseIP(r.Value)
		if ip == nil || ip.To4() != nil {
			return fmt.Errorf("AAAA record requires an IPv6 address, got %q", r.Value)
		}
	case "CNAME", "NS", "MX", "SRV":
		if r.Value == "" {
			return fmt.Errorf("%s record requires a target host", r.Type)
		}
	case "TXT":
		if r.Value == "" {
			return fmt.Errorf("TXT record requires a value")
		}
	default:
		return fmt.Errorf("unsupported record type %q", r.Type)
	}
	if (r.Type == "MX" || r.Type == "SRV") && r.Priority < 0 {
		return fmt.Errorf("%s record requires a non-negative priority", r.Type)
	}
	return nil
}

// RenderZone produces an RFC 1035 zone file for a domain and its records.
func RenderZone(domain store.Domain, records []store.DNSRecord) string {
	origin := domain.Name + "."
	serial := time.Now().UTC().Format("2006010215")

	var b strings.Builder
	fmt.Fprintf(&b, "; Zone file for %s — generated by GoshPanel\n", domain.Name)
	fmt.Fprintf(&b, "$ORIGIN %s\n$TTL 3600\n\n", origin)
	fmt.Fprintf(&b, "@\tIN\tSOA\tns1.%s hostmaster.%s (\n", origin, origin)
	fmt.Fprintf(&b, "\t\t%s ; serial\n\t\t7200       ; refresh\n\t\t3600       ; retry\n\t\t1209600    ; expire\n\t\t3600 )     ; minimum\n\n", serial)

	for _, r := range records {
		name := r.Name
		if name == "@" || name == domain.Name {
			name = "@"
		}
		ttl := r.TTL
		if ttl == 0 {
			ttl = 3600
		}
		value := r.Value
		switch r.Type {
		case "TXT":
			value = fmt.Sprintf("%q", r.Value)
		case "MX", "SRV":
			value = fmt.Sprintf("%d %s", r.Priority, ensureDot(r.Value))
		case "CNAME", "NS":
			value = ensureDot(r.Value)
		}
		fmt.Fprintf(&b, "%s\t%d\tIN\t%s\t%s\n", name, ttl, r.Type, value)
	}
	return b.String()
}

// ensureDot makes a hostname fully qualified for zone-file use.
func ensureDot(host string) string {
	if strings.HasSuffix(host, ".") {
		return host
	}
	return host + "."
}
