// Package cron validates cron expressions, renders a crontab and applies
// it via the system crontab binary (a process call, not cgo).
package cron

import (
	"bytes"
	"context"
	"fmt"
	"os/exec"
	"strconv"
	"strings"

	"github.com/schmorrison/goshpanel/internal/store"
)

// fieldRange describes the legal bounds of one cron field.
type fieldRange struct {
	name string
	min  int
	max  int
}

var fields = []fieldRange{
	{"minute", 0, 59},
	{"hour", 0, 23},
	{"day of month", 1, 31},
	{"month", 1, 12},
	{"day of week", 0, 7},
}

// ValidateSchedule checks a standard 5-field cron expression, including
// steps (*/5), ranges (1-5) and lists (1,2,3). @-shortcuts are accepted.
func ValidateSchedule(expr string) error {
	expr = strings.TrimSpace(expr)
	switch expr {
	case "@hourly", "@daily", "@weekly", "@monthly", "@yearly", "@annually", "@midnight", "@reboot":
		return nil
	}
	parts := strings.Fields(expr)
	if len(parts) != 5 {
		return fmt.Errorf("expected 5 fields (minute hour day month weekday), got %d", len(parts))
	}
	for i, part := range parts {
		if err := validateField(part, fields[i]); err != nil {
			return err
		}
	}
	return nil
}

func validateField(part string, fr fieldRange) error {
	for _, item := range strings.Split(part, ",") {
		expr := item
		if i := strings.Index(expr, "/"); i >= 0 {
			step := expr[i+1:]
			if n, err := strconv.Atoi(step); err != nil || n <= 0 {
				return fmt.Errorf("invalid step %q in %s field", step, fr.name)
			}
			expr = expr[:i]
		}
		if expr == "*" {
			continue
		}
		bounds := strings.SplitN(expr, "-", 2)
		for _, b := range bounds {
			n, err := strconv.Atoi(b)
			if err != nil {
				return fmt.Errorf("invalid value %q in %s field", b, fr.name)
			}
			if n < fr.min || n > fr.max {
				return fmt.Errorf("%s value %d out of range %d-%d", fr.name, n, fr.min, fr.max)
			}
		}
		if len(bounds) == 2 {
			lo, _ := strconv.Atoi(bounds[0])
			hi, _ := strconv.Atoi(bounds[1])
			if lo > hi {
				return fmt.Errorf("descending range %q in %s field", expr, fr.name)
			}
		}
	}
	return nil
}

// RenderCrontab produces the crontab text for the panel's jobs.
func RenderCrontab(jobs []store.CronJob) string {
	var b strings.Builder
	b.WriteString("# Crontab generated by GoshPanel — do not edit by hand.\n")
	for _, j := range jobs {
		if j.Comment != "" {
			fmt.Fprintf(&b, "# %s\n", j.Comment)
		}
		fmt.Fprintf(&b, "%s %s\n", j.Schedule, j.Command)
	}
	return b.String()
}

// Apply installs the rendered crontab for the current user via the
// crontab binary.
func Apply(ctx context.Context, jobs []store.CronJob) error {
	bin, err := exec.LookPath("crontab")
	if err != nil {
		return fmt.Errorf("crontab binary not found in PATH")
	}
	cmd := exec.CommandContext(ctx, bin, "-")
	cmd.Stdin = bytes.NewBufferString(RenderCrontab(jobs))
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("crontab install failed: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}
