package firewall

import (
	"fmt"
	"strings"

	"github.com/schmorrison/goshpanel/internal/store"
)

// RenderNftables produces an nftables ruleset from panel rules.
func RenderNftables(rules []store.FirewallRule) string {
	var b strings.Builder
	b.WriteString("# Generated by GoshPanel — nftables ruleset\n")
	b.WriteString("flush ruleset\n")
	b.WriteString("table inet goshpanel {\n")
	b.WriteString("  chain input {\n")
	b.WriteString("    type filter hook input priority 0; policy accept;\n")
	b.WriteString("    # always allow established\n")
	b.WriteString("    ct state established,related accept\n")
	b.WriteString("    # loopback\n")
	b.WriteString("    iif lo accept\n")
	for _, r := range rules {
		if !r.Enabled {
			continue
		}
		action := "accept"
		if r.Action == "drop" || r.Action == "reject" {
			action = r.Action
		}
		proto := strings.TrimSpace(r.Protocol)
		if proto == "" {
			proto = "tcp"
		}
		fmt.Fprintf(&b, "    %s dport %d %s comment \"%s\"\n", proto, r.Port, action, escapeComment(r.Comment))
	}
	b.WriteString("  }\n}\n")
	return b.String()
}

func escapeComment(s string) string {
	return strings.ReplaceAll(s, "\"", "'")
}
