package waf

import (
	"fmt"
	"strings"

	"github.com/schmorrison/goshpanel/internal/store"
)

// CaddySnippet returns a Coraza WAF handler block for a domain.
func CaddySnippet(site store.WAFSite) string {
	if !site.Enabled {
		return ""
	}
	policy := strings.TrimSpace(site.PolicyPath)
	if policy == "" {
		policy = "/etc/coraza/coraza.conf"
	}
	return fmt.Sprintf(`
	coraza_waf {
		directives %s
	}
`, policy)
}

// RenderCorazaConfig produces a minimal Coraza config stub.
func RenderCorazaConfig() string {
	return `# Generated by GoshPanel — Coraza OWASP CRS stub
SecRuleEngine On
Include @owasp_crs/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
Include @owasp_crs/REQUEST-901-INITIALIZATION.conf
Include @owasp_crs/REQUEST-905-COMMON-EXCEPTIONS.conf
Include @owasp_crs/REQUEST-911-METHOD-ENFORCEMENT.conf
Include @owasp_crs/REQUEST-913-SCANNER-DETECTION.conf
Include @owasp_crs/REQUEST-920-PROTOCOL-ENFORCEMENT.conf
Include @owasp_crs/RESPONSE-959-BLOCKING-EVALUATION.conf
Include @owasp_crs/RESPONSE-980-CORRELATION.conf
`
}
