// Package domains validates hosted-site definitions and renders a
// Caddyfile so a Go-native web server (Caddy) can serve them. Applying
// the config is a process call to the caddy binary when present.
package domains

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/schmorrison/goshpanel/internal/store"
)

var domainRe = regexp.MustCompile(`^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$`)

// ValidateName checks that name is a plausible fully-qualified domain.
func ValidateName(name string) error {
	name = strings.ToLower(strings.TrimSpace(name))
	if !domainRe.MatchString(name) {
		return fmt.Errorf("invalid domain name %q", name)
	}
	return nil
}

// CaddyContext holds everything needed to render a Caddyfile.
type CaddyContext struct {
	Domains       []store.Domain
	AccessLogPath string
	Webmail       store.WebmailSettings
	Redirects     []store.RedirectRule
	Aliases       []store.DomainAlias
	WAFSites      []store.WAFSite
	ShortLinks    []store.ShortLink
}

// RenderCaddyfile produces a Caddyfile for the given domains.
func RenderCaddyfile(domains []store.Domain, accessLogPath string, webmail store.WebmailSettings) string {
	return RenderCaddyfileFull(CaddyContext{Domains: domains, AccessLogPath: accessLogPath, Webmail: webmail})
}

// RenderCaddyfileFull renders with redirects, aliases, and WAF snippets.
func RenderCaddyfileFull(ctx CaddyContext) string {
	var b strings.Builder
	if ctx.AccessLogPath != "" {
		b.WriteString("{\n")
		fmt.Fprintf(&b, "\tlog {\n\t\toutput file %s {\n\t\t\troll_size 10MiB\n\t\t\troll_keep 5\n\t\t}\n\t\tformat json\n\t}\n}\n\n", ctx.AccessLogPath)
	}
	b.WriteString("# Generated by GoshPanel — do not edit by hand.\n\n")
	if ctx.Webmail.Enabled && ctx.Webmail.Host != "" && ctx.Webmail.Upstream != "" {
		fmt.Fprintf(&b, "%s {\n\treverse_proxy %s\n}\n\n", ctx.Webmail.Host, ctx.Webmail.Upstream)
	}
	for _, r := range ctx.Redirects {
		if !r.Enabled || r.FromHost == "" || r.ToURL == "" {
			continue
		}
		status := r.Status
		if status <= 0 {
			status = 301
		}
		fmt.Fprintf(&b, "%s {\n\tredir %s %d\n}\n\n", r.FromHost, r.ToURL, status)
	}
	aliasTarget := map[string]string{}
	for _, a := range ctx.Aliases {
		aliasTarget[strings.ToLower(a.AliasHost)] = a.TargetHost
	}
	wafFor := map[string]store.WAFSite{}
	for _, w := range ctx.WAFSites {
		if w.Enabled {
			wafFor[strings.ToLower(w.Host)] = w
		}
	}
	sorted := make([]store.Domain, len(ctx.Domains))
	copy(sorted, ctx.Domains)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	for _, d := range sorted {
		writeSiteBlock(&b, d.Name, d.Root, d.Upstream, wafFor[strings.ToLower(d.Name)])
	}
	for alias, target := range aliasTarget {
		if dom, ok := domainByName(sorted, target); ok {
			writeSiteBlock(&b, alias, dom.Root, dom.Upstream, wafFor[alias])
		}
	}
	writeShortLinkBlocks(&b, ctx.ShortLinks)
	return b.String()
}

func writeShortLinkBlocks(b *strings.Builder, links []store.ShortLink) {
	byHost := map[string][]store.ShortLink{}
	for _, l := range links {
		host := strings.TrimSpace(l.Host)
		if host == "" {
			continue
		}
		byHost[strings.ToLower(host)] = append(byHost[strings.ToLower(host)], l)
	}
	hosts := make([]string, 0, len(byHost))
	for h := range byHost {
		hosts = append(hosts, h)
	}
	sort.Strings(hosts)
	for _, host := range hosts {
		fmt.Fprintf(b, "%s {\n", host)
		for _, l := range byHost[host] {
			code := strings.TrimPrefix(strings.TrimSpace(l.Code), "/")
			fmt.Fprintf(b, "\tredir /%s %s 302\n", code, l.TargetURL)
		}
		b.WriteString("}\n\n")
	}
}

func domainByName(domains []store.Domain, name string) (store.Domain, bool) {
	name = strings.ToLower(name)
	for _, d := range domains {
		if strings.ToLower(d.Name) == name {
			return d, true
		}
	}
	return store.Domain{}, false
}

func writeSiteBlock(b *strings.Builder, host, root, upstream string, waf store.WAFSite) {
	fmt.Fprintf(b, "%s {\n", host)
	if waf.Host != "" {
		b.WriteString("\t# Coraza WAF — requires caddy-coraza plugin\n")
		fmt.Fprintf(b, "\t# policy: %s\n", waf.PolicyPath)
	}
	switch {
	case upstream != "" && root != "":
		fmt.Fprintf(b, "\troot * %s\n", root)
		b.WriteString("\tfile_server\n")
		fmt.Fprintf(b, "\treverse_proxy /api/* %s\n", upstream)
	case upstream != "":
		fmt.Fprintf(b, "\treverse_proxy %s\n", upstream)
	default:
		fmt.Fprintf(b, "\troot * %s\n", root)
		b.WriteString("\tfile_server\n")
	}
	b.WriteString("}\n\n")
}

// WriteCaddyfile renders and writes the Caddyfile to path.
func WriteCaddyfile(domains []store.Domain, path, accessLogPath string, webmail store.WebmailSettings) error {
	return WriteCaddyfileFull(CaddyContext{Domains: domains, AccessLogPath: accessLogPath, Webmail: webmail}, path)
}

// WriteCaddyfileFull writes a full Caddyfile context.
func WriteCaddyfileFull(ctx CaddyContext, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(RenderCaddyfileFull(ctx)), 0o644); err != nil {
		return fmt.Errorf("write caddyfile: %w", err)
	}
	return nil
}

// ApplyCaddyfile reloads a running caddy with the config at path.
// Returns a descriptive error if the caddy binary is unavailable.
func ApplyCaddyfile(ctx context.Context, path string) error {
	bin, err := exec.LookPath("caddy")
	if err != nil {
		return fmt.Errorf("caddy binary not found in PATH; Caddyfile written to %s for manual use", path)
	}
	out, err := exec.CommandContext(ctx, bin, "reload", "--config", path, "--adapter", "caddyfile").CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy reload failed: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}
