// Package domains validates hosted-site definitions and renders a
// Caddyfile so a Go-native web server (Caddy) can serve them. Applying
// the config is a process call to the caddy binary when present.
package domains

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/schmorrison/goshpanel/internal/store"
)

var domainRe = regexp.MustCompile(`^([a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,}$`)

// ValidateName checks that name is a plausible fully-qualified domain.
func ValidateName(name string) error {
	name = strings.ToLower(strings.TrimSpace(name))
	if !domainRe.MatchString(name) {
		return fmt.Errorf("invalid domain name %q", name)
	}
	return nil
}

// RenderCaddyfile produces a Caddyfile for the given domains. Each domain
// serves its static root and/or reverse-proxies to an upstream.
func RenderCaddyfile(domains []store.Domain) string {
	sorted := make([]store.Domain, len(domains))
	copy(sorted, domains)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b strings.Builder
	b.WriteString("# Generated by GoshPanel — do not edit by hand.\n\n")
	for _, d := range sorted {
		fmt.Fprintf(&b, "%s {\n", d.Name)
		switch {
		case d.Upstream != "" && d.Root != "":
			fmt.Fprintf(&b, "\troot * %s\n", d.Root)
			b.WriteString("\tfile_server\n")
			fmt.Fprintf(&b, "\treverse_proxy /api/* %s\n", d.Upstream)
		case d.Upstream != "":
			fmt.Fprintf(&b, "\treverse_proxy %s\n", d.Upstream)
		default:
			fmt.Fprintf(&b, "\troot * %s\n", d.Root)
			b.WriteString("\tfile_server\n")
		}
		b.WriteString("}\n\n")
	}
	return b.String()
}

// WriteCaddyfile renders and writes the Caddyfile to path.
func WriteCaddyfile(domains []store.Domain, path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("create config dir: %w", err)
	}
	if err := os.WriteFile(path, []byte(RenderCaddyfile(domains)), 0o644); err != nil {
		return fmt.Errorf("write caddyfile: %w", err)
	}
	return nil
}

// ApplyCaddyfile reloads a running caddy with the config at path.
// Returns a descriptive error if the caddy binary is unavailable.
func ApplyCaddyfile(ctx context.Context, path string) error {
	bin, err := exec.LookPath("caddy")
	if err != nil {
		return fmt.Errorf("caddy binary not found in PATH; Caddyfile written to %s for manual use", path)
	}
	out, err := exec.CommandContext(ctx, bin, "reload", "--config", path, "--adapter", "caddyfile").CombinedOutput()
	if err != nil {
		return fmt.Errorf("caddy reload failed: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}
